# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x0c\x45\x63hoResponse\x12\x16\n\x0e\x65\x63hoed_message\x18\x01 \x01(\t29\n\x0b\x45\x63hoService\x12*\n\x0b\x45\x63hoMessage\x12\x0c.EchoRequest\x1a\r.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=14
  _globals['_ECHOREQUEST']._serialized_end=44
  _globals['_ECHORESPONSE']._serialized_start=46
  _globals['_ECHORESPONSE']._serialized_end=84
  _globals['_ECHOSERVICE']._serialized_start=86
  _globals['_ECHOSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
